version: '3.7'

services:
  webdav-nginx:
    container_name: webdav
    build: .
    image: rpi-nginx-webdav:latest
    ports:
      - 8432:8080
    volumes:
      - ./media:/media
    environment:
      - WEBDAV_USERNAME=${USERNAME:-user}
      - WEBDAV_PASSWORD=${PASSWORD:-pw}
      - UID=${UID}
    restart: unless-stopped
